- name: Config Languague
  command: locale-gen es_ES.UTF-8

- name: Installing Packets
  apt: name={{ item }} update_cache=yes state=present
  with_items:
  - vsftpd
  - openjdk-7-jre
  - unzip

- replace:
    dest=/etc/vsftpd.conf
    regexp='anonymous_enable=NO'
    replace='anonymous_enable=YES'

- replace:
    dest=/etc/vsftpd.conf
    regexp='anonymous_enable=NO'
    replace='anonymous_enable=YES'

- replace:
    dest=/etc/vsftpd.conf
    regexp='#ftpd_banner=Welcome to blah FTP service.'
    replace='ftpd_banner={{FTPBANNER}}'

- name: pam.d for vsftpd 
  blockinfile:
    dest: /etc/pam.d/vsftpd
    block: |
      auth required pam_mysql.so user=vagrant passwd=vagrant host=192.168.80.4 db=vsftpd table=user usercolumn=user passwdcolumn=pass crypt=2
      account required pam_mysql.so user=vagrant passwd=vagrant host=192.168.80.4 db=vsftpd table=user usercolumn=user passwdcolumn=pass crypt=2

- name: Restarting vsftpd
  service:
    name: vsftpd
    state: restarted

- name: Downloading Openfire
  get_url:
    url: https://www.igniterealtime.org/downloadServlet?filename=openfire/openfire_4.1.2_all.deb
    dest: /tmp/openfire.deb
    validate_certs: no

- name: Install Openfire
  apt:
    deb: /tmp/openfire.deb 
