- name: Config Languague
  command: locale-gen es_ES.UTF-8

- name: Installing Packets
  apt: name={{ item }} update_cache=yes state=present
  with_items:
  - vsftpd
  - openjdk-7-jre
  - unzip

- replace:
    dest=/etc/vsftpd.conf
    regexp='anonymous_enable=NO'
    replace='anonymous_enable=YES'

- replace:
    dest=/etc/vsftpd.conf
    regexp='#ftpd_banner=Welcome to blah FTP service.'
    replace='ftpd_banner={{FTPBANNER}}'

- name: Restarting vsftpd
  service:
    name: vsftpd
    state: restarted

- name: Downloading Openfire
  get_url:
    url: https://www.igniterealtime.org/downloadServlet?filename=openfire/openfire_4.1.2_all.deb
    dest: /tmp/openfire.deb
    validate_certs: no

- name: Install Openfire
  apt:
    deb: /tmp/openfire.deb 
