---
- hosts: DB
  become: true

  vars_prompt:

    - name: "DOMAIN"
      prompt: "Enter LDAP domain (example.com): "
      private: no

    - name: "SITE"
      prompt: "Enter LDAP organization: "
      private: no

    - name: "SECRET"
      prompt: "Enter LDAP admin password: "
      private: no

  roles:
   - {role: ansible-openldap } 

  tasks:

#   - script: adduser.sh

