---
- hosts: ftpserver
  become: true

  vars_prompt:

    - name: "FTPBANNER"
      prompt: "Enter banner for FTP"
      private: no

  tasks:
        - name: actualizando la cache de apt
          apt: update_cache=yes

        - include: ftp.yml
